### ISSUE TITLE
Ignores annotation if a previous test fails

### ISSUE THREAD

**Issue by PatrickRose** [akeneo/PhpSpecSkipExampleExtension#8]
I've just been adding this in - but it seems that it ignores the annotation if a previous spec fails in some way?

**Comment by nidup** [comment]
Hi @PatrickRose 

Wow, sorry for my super late answer. I didn't reproduced it on the last version, maybe not anymore the case.

Don't hesitate to re-open the issue with an example to reproduce it if you still have the issue.

Have a good day.
