### ISSUE TITLE
It requires PhpSpec 2.1*, why not ~2.1?

### ISSUE THREAD

**Issue by pamil** [akeneo/PhpSpecSkipExampleExtension#9]
This extension forces me to use PhpSpec `2.1.*`, while I want to use `2.3` instead. Can you make it `~2.1`? I guess there's no BC introduced between `2.1` and `2.3`.

**Comment by pjedrzejewski** [comment]
@jjanvier @nidup @BitOne Guys? :) Would be cool to be able to use this extension with latest version of phpspec in Sylius. :)

**Comment by nidup** [comment]
Fixed in v1.2.0, thank you @stloyd for the PR! don't hesitate if you encounter any issue :)
